### ISSUE TITLE
"libscrypt": Reducing duplication of effort.

### ISSUE THREAD

**Issue by skull-squadron** [informatikr/scrypt#1]
Basically, having one libscrypt makes things easier.  Otherwise, improvements in one binding don't get propagated upstream to others, etc, etc.

Also, I'm open to placing these bindings in the readme, `cabal install scrypt` and author attribution at your option... up to you.

**Comment by informatikr** [comment]
Sorry for my late answer, I have been on a vacation.

I must say I can't really follow what you are talking about. Google tells me you had a repository "libscrypt" on github, but I get a 404 when I follow the link (https://github.com/steakknife/libscrypt). Maybe it is a private repo now? Is it a Haskell project? A distribution of Colin Percival's (or somebody else's) C code that my Haskell library could link to? Or something else?

Can you elaborate, please? Thank you.

**Comment by skull-squadron** [comment]
I'm the one that asks questions, stalker.  Adios.
