### ISSUE TITLE
Customizable bufLen

### ISSUE THREAD

**Issue by markschultz** [informatikr/scrypt#3]
Is there a reason why bufLen is static at 64?

**Comment by informatikr** [comment]
It is a good default for most use cases. Not exposing that parameter makes it convenient to use and protects against creating irresponsibly short keys. If I remember correctly, I found scrypt bindings for several other languages that made the same choice.

Do you need a different key length?

**Comment by markschultz** [comment]
I am trying to get enough bytes to fill a 521-bit EC key. Maybe you could expose a method like scryptParams that also accepts a buflen that is only valid if bufLen > 64? In my view one of the strengths of scrypt is arbitrary length output. I agree 64 bytes is a good default that is perfect 99% of the time.

Edit:
I know i can use other methods to get the few extra bits in a cryptographically secure way but it would be nice if i could just specify bufLen as 66 then drop 7 bits to get to 521.

**Comment by informatikr** [comment]
Hi Mark,

scrypt version 0.4.0 on Hackage exposes the `scryptParamsLen` function which does what you need. Let me know if you find any other issues with scrypt, I always like to hear from users of my libraries.

**Comment by markschultz** [comment]
Exactly what i was looking for, thanks!
