### ISSUE TITLE
Trailing NUL characters in passwords are ignored

### ISSUE THREAD

**Issue by kuliniew** [informatikr/scrypt#5]
The functions encryptPass, verifyPass, etc. ignore trailing NUL characters in passwords, so the passwords "foobar" and "foobar\NUL" are treated as equivalent -- the password "foobar" will successfully verify with scrypted password "foobar\NUL" and vice versa.  NUL characters appearing elsewhere in passwords are respected, so "foobar" and "foo\NULbar" are _not_ treated as equivalent.  Nor are "foo" and "foo\NULbar" treated as equivalent, so it doesn't appear as though passwords are simply being truncated at the first NUL.

The following program demonstrates the bug.  It inserts a NUL character inside the string "foobar" in a few different positions, and outputs cases where two distinct password strings (e.g. "foobar" and "foobar\NUL") are treated equivalently.

http://lpaste.net/7630761935448834048

This behavior occurs with the scrypt-0.4.0 package on Hackage.

Granted, it's probably unlikely that someone would put a NUL inside a password, but it could conceivably happen for randomly-generated passwords for machine-to-machine authentication, where typeability isn't a concern.

**Comment by informatikr** [comment]
Hi kuliniew,

Since this behavior comes from scrypt itself, not my Haskell bindings, I forwarded your question to Colin Percival. Here is his reply:

> Yes, this is normal; it results from the identical behaviour in HMAC-*, since
> the only places scrypt handles the password directly, it is being input to
> HMAC-SHA256 as a key.
> 
> Since this only affects trailing NULs I don't see it as being a problem --
> especially given that passwords generally don't include any NUL characters.

So it appears that everything is fine. Thanks for the report, please let me know when you find any other issues with scrypt.
