### ISSUE TITLE
Include scrypt in stackage

### ISSUE THREAD

**Issue by wereHamster** [informatikr/scrypt#7]
Would be nice if scrypt was part of stackage, so that I didn't have to include it in extra-deps.

There is practically no effort needed on your side (I have a few packages in stackage myself). Plus, you'll automatically be notified when your package fails to build with newer versions of its dependencies (as you don't have any upper bounds).

**Comment by informatikr** [comment]
Pull request is merged into stackage.

**Comment by wereHamster** [comment]
Very nice, thank you.
